// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  spaces = 22,
  newline = 23,
  graph = 1,
  kwstrict = 2,
  kwgraph = 3,
  kwdigraph = 4,
  ID = 5,
  node_stmt = 6,
  compass_pt = 7,
  edge_stmt = 9,
  subgraph = 10,
  kwsubgraph = 11,
  attr_stmt = 12,
  kwnode = 13,
  kwedge = 14
